workflows:
  react_native_tally:
    name: React Native Tally App
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_credentials # Ensure you create this group in Codemagic UI with EXPO_TOKEN
      vars:
        NODE_VERSION: 18
        CI: 1
    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Reinstall EAS CLI
        script: npm install -g eas-cli@latest

      - name: Verify Expo CLI
        script: |
          if ! command -v expo &> /dev/null; then
            echo "Expo CLI not found! Installing..."
            npm install -g expo-cli
          fi
          expo --version

      - name: Create eas.json if missing
        script: |
          if [ ! -f "eas.json" ]; then
            echo '{
              "build": {
                "development": {
                  "extends": "default",
                  "distribution": "internal",
                  "android": { "buildType": "apk" },
                  "ios": { "simulator": true }
                }
              }
            }' > eas.json
          fi

      - name: Authenticate with Expo using EXPO_TOKEN
        script: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "❌ Error: EXPO_TOKEN is not set. Please add it in Codemagic environment variables."
            exit 1
          else
            echo "✅ Expo authentication successful."
            export EXPO_TOKEN=$EXPO_TOKEN
            npx expo login --token $EXPO_TOKEN
          fi

      - name: Build Android APK
        script: |
          export EXPO_TOKEN=$EXPO_TOKEN
          npx eas build --platform android --profile development --non-interactive

      - name: Build iOS IPA
        script: |
          export EXPO_TOKEN=$EXPO_TOKEN
          npx eas build --platform ios --profile development --non-interactive

    artifacts:
      - "**/*.apk"  # Adjusted for correct APK output path
      - "**/*.ipa"  # Adjusted for correct IPA output path

    publishing:
      email:
        recipients:
          - "kengyap@upm.edu.my"
          - "elarabijnr@gmail.com"
