workflows:
  react_native_tally:
    name: React Native Tally App
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_VERSION: 18
        CI: 1
        # EXPO_TOKEN must be set in Codemagic UI under secure environment variables
    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Reinstall EAS CLI
        script: npm install -g eas-cli@latest

      - name: Verify Expo CLI
        script: |
          if ! command -v expo &> /dev/null; then
            echo "Expo CLI not found! Installing..."
            npm install -g expo-cli
          fi
          expo --version

      - name: Debug EXPO_TOKEN
        script: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "❌ EXPO_TOKEN is NOT set! Ensure it's in Codemagic secure environment variables."
            exit 1
          else
            echo "✅ EXPO_TOKEN is set (Masked): ${EXPO_TOKEN:0:4}********"
          fi

      - name: Create eas.json if missing
        script: |
          if [ ! -f "eas.json" ]; then
            cat <<EOL > eas.json
{
  "build": {
    "development": {
      "distribution": "internal",
      "android": { "buildType": "apk" },
      "ios": { "simulator": true }
    }
  }
}
EOL
          fi

      - name: Authenticate with Expo using EXPO_TOKEN
        script: |
          export EXPO_TOKEN="$EXPO_TOKEN"
          echo "EXPO_TOKEN exported"
          
          echo "🔍 Checking Expo authentication..."
          if ! npx eas whoami; then
            echo "❌ Authentication failed! Check if EXPO_TOKEN is valid or refresh it."
            exit 1
          fi

      - name: Build Android APK
        script: |
          export EXPO_TOKEN="$EXPO_TOKEN"
          npx eas build --platform android --profile development --non-interactive || exit 1

      - name: Build iOS IPA
        script: |
          export EXPO_TOKEN="$EXPO_TOKEN"
          npx eas build --platform ios --profile development --non-interactive || exit 1

    artifacts:
      - "**/*.apk"
      - "**/*.ipa"

    publishing:
      email:
        recipients:
          - "kengyap@upm.edu.my"
          - "elarabijnr@gmail.com"
