workflows:
  react_native_tally:
    name: React Native Tally App
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_VERSION: 18
        CI: 1
    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Install EAS CLI
        script: npm install -g eas-cli@latest

      - name: Verify Expo CLI
        script: |
          if ! command -v expo &> /dev/null; then
            echo "Expo CLI not found! Installing..."
            npm install -g expo-cli@latest
          fi
          expo --version

      - name: Debug EXPO_TOKEN
        script: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "❌ EXPO_TOKEN is NOT set! Ensure it's in Codemagic secure environment variables."
            exit 1
          else
            echo "✅ EXPO_TOKEN is set (Masked): ${EXPO_TOKEN:0:4}********"
          fi

      - name: Ensure eas.json Exists
        script: |
          if [ ! -f "eas.json" ]; then
            cat <<EOF > eas.json
            {
              "build": {
                "development": {
                  "distribution": "internal",
                  "android": { "buildType": "apk" },
                  "ios": { "simulator": true }
                }
              }
            }
            EOF
          fi

      - name: Authenticate with Expo using EXPO_TOKEN
        script: |
          echo "🔍 Checking Expo authentication..."
          if ! eas whoami; then
            echo "❌ Authentication failed! Check if EXPO_TOKEN is valid or refresh it."
            exit 1
          fi

      - name: Build Android APK
        script: |
          npx eas build --platform android --profile development --non-interactive || { echo "❌ Android build failed"; exit 1; }

      - name: Build iOS IPA
        script: |
          npx eas build --platform ios --profile development --non-interactive || { echo "❌ iOS build failed"; exit 1; }

    artifacts:
      - "**/*.apk"
      - "**/*.ipa"

    publishing:
      email:
        recipients:
          - "kengyap@upm.edu.my"
          - "elarabijnr@gmail.com"
