workflows:
  react_native_tally:
    name: React Native Tally App
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_credentials # Ensure you create this group in Codemagic UI
      vars:
        NODE_VERSION: 18
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Reinstall EAS CLI
        script: npm install -g eas-cli@latest
      - name: Create eas.json if missing
        script: |
          if [ ! -f "eas.json" ]; then
            echo '{
              "build": {
                "development": {
                  "distribution": "internal",
                  "android": { "buildType": "apk" },
                  "ios": { "simulator": true }
                }
              }
            }' > eas.json
          fi
      - name: Log in to Expo
        script: npx expo login --non-interactive --username "$EXPO_USERNAME" --password "$EXPO_PASSWORD"
      - name: Build Android APK
        script: npx eas build --platform android --profile development --non-interactive
      - name: Build iOS IPA
        script: npx eas build --platform ios --profile development --non-interactive
    artifacts:
      - build/**/android/**/*.apk
      - build/**/ios/**/*.ipa
    publishing:
      email:
        recipients:
          - "kengyap@upm.edu.my"
          - "elarabijnr@gmail.com"
