workflows:
  react_native_tally:
    name: React Native Tally App
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_credentials # Ensure you create this group in Codemagic UI
      vars:
        NODE_VERSION: 18
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: npx eas build --platform android --profile preview --non-interactive
      - name: Build iOS IPA
        script: npx eas build --platform ios --profile preview --non-interactive
    artifacts:
      - build/**/android/**/*.apk
      - build/**/ios/**/*.ipa
    publishing:
      email:
        recipients:
          - "kengyap@upm.edu.my"
          - "elarabijnr@gmail.com"
