workflows:
  react_native_tally:
    name: React Native Tally App
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_VERSION: 18
        CI: 1
        # EXPO_TOKEN is set in Codemagic environment variables, NOT here

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Reinstall EAS CLI
        script: npm install -g eas-cli@latest

      - name: Verify Expo CLI
        script: |
          if ! command -v expo &> /dev/null; then
            echo "Expo CLI not found! Installing..."
            npm install -g expo-cli
          fi
          expo --version

      - name: Debug EXPO_TOKEN (for debugging only)
        script: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "❌ EXPO_TOKEN is NOT set!"
            exit 1
          else
            echo "✅ EXPO_TOKEN is set (Masked): ${EXPO_TOKEN:0:4}********"
          fi

      - name: Create eas.json if missing
        script: |
          if [ ! -f "eas.json" ]; then
            cat <<EOL > eas.json
            {
              "build": {
                "development": {
                  "extends": "default",
                  "distribution": "internal",
                  "android": { "buildType": "apk" },
                  "ios": { "simulator": true }
                }
              }
            }
            EOL
          fi

      - name: Authenticate with Expo
        script: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "❌ EXPO_TOKEN is not set. Please add it in Codemagic environment variables."
            exit 1
          fi

          echo "✅ EXPO_TOKEN is set. Proceeding with authentication..."
          npx eas whoami  # Correct way to authenticate

      - name: Build Android APK
        script: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "❌ EXPO_TOKEN is not set."
            exit 1
          fi
          npx eas build --platform android --profile development --non-interactive || exit 1  # Exit on failure

      - name: Build iOS IPA
        script: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "❌ EXPO_TOKEN is not set."
            exit 1
          fi
          npx eas build --platform ios --profile development --non-interactive || exit 1  # Exit on failure

    artifacts:
      - "**/*.apk"
      - "**/*.ipa"

    publishing:
      email:
        recipients:
          - "kengyap@upm.edu.my"
          - "elarabijnr@gmail.com"
